package com.gradingplatform.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

/** A row of `courses` (V2). */
@Entity
@Table(name = "courses")
public class Course {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "title", nullable = false)
    private String title;

    @Column(name = "description")
    private String description;

    /** The owning teacher's `users.id`. Kept as a plain id: no query needs the `User` loaded. */
    @Column(name = "teacher_id", nullable = false)
    private Long teacherId;

    /** What students type to join; unique. Generated by `EnrollCodeGenerator`, never client-supplied. */
    @Column(name = "enroll_code", nullable = false)
    private String enrollCode;

    /** Set by the database default (`NOW()`); read back after the insert, never written by us. */
    @Generated(event = EventType.INSERT)
    @Column(name = "created_at", insertable = false, updatable = false)
    private Instant createdAt;

    /** For JPA only. */
    protected Course() {}

    public Course(String title, String description, Long teacherId, String enrollCode) {
        this.title = title;
        this.description = description;
        this.teacherId = teacherId;
        this.enrollCode = enrollCode;
    }

    /** The two fields a teacher may change. The owner and the enrollment code never change. */
    public void update(String title, String description) {
        this.title = title;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public Long getTeacherId() {
        return teacherId;
    }

    public String getEnrollCode() {
        return enrollCode;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
