package com.gradingplatform.backend.dto;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.gradingplatform.backend.entity.TestCase;
import com.gradingplatform.backend.entity.TestVisibility;
import java.lang.reflect.RecordComponent;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Test;

/** 3.5b: the student shape of a test case cannot carry a hidden test's content. */
class StudentTestCaseResponseTests {

    private static final String SECRET_NAME = "SECRET-NAME-edge-case-with-empty-list";
    private static final String SECRET_INPUT = "SECRET-INPUT-42";
    private static final String SECRET_OUTPUT = "SECRET-OUTPUT-43";

    private final ObjectMapper json = new ObjectMapper();

    private static TestCase test(long id, String name, TestVisibility visibility, int position) {
        // The entity's id is generated by the database; the test only needs it for the mapping.
        TestCase t = new TestCase(
                7L,
                1L,
                name,
                visibility == TestVisibility.HIDDEN ? SECRET_INPUT : "public in",
                visibility == TestVisibility.HIDDEN ? SECRET_OUTPUT : "public out",
                visibility,
                3,
                position);
        try {
            var field = TestCase.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(t, id);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(e);
        }
        return t;
    }

    private static List<String> componentNames(Class<?> record) {
        return Arrays.stream(record.getRecordComponents())
                .map(RecordComponent::getName)
                .toList();
    }

    @Test
    void aHiddenTestHasNoComponentThatCouldHoldItsContent() {
        assertThat(componentNames(StudentTestCaseResponse.HiddenTest.class))
                .containsExactly("id", "name", "visibility", "position");
    }

    @Test
    void aPublicTestHasExactlyTheFieldsAStudentNeeds() {
        assertThat(componentNames(StudentTestCaseResponse.PublicTest.class))
                .containsExactly("id", "name", "input", "expectedOutput", "visibility", "weight", "position");
    }

    @Test
    void hiddenTestsAreMaskedAndNumberedAmongThemselvesInRunOrder() {
        List<TestCase> tests = List.of(
                test(1, "first public", TestVisibility.PUBLIC, 1),
                test(2, SECRET_NAME + "-a", TestVisibility.HIDDEN, 2),
                test(3, "second public", TestVisibility.PUBLIC, 3),
                test(4, SECRET_NAME + "-b", TestVisibility.HIDDEN, 4));

        List<StudentTestCaseResponse> mapped =
                StudentTestCasesResponse.of(tests).tests();

        assertThat(mapped).hasSize(4);
        assertThat(mapped.get(0)).isInstanceOf(StudentTestCaseResponse.PublicTest.class);
        assertThat(mapped.get(1))
                .isEqualTo(new StudentTestCaseResponse.HiddenTest(2L, "Hidden test 1", TestVisibility.HIDDEN, 2));
        assertThat(mapped.get(2)).isInstanceOf(StudentTestCaseResponse.PublicTest.class);
        assertThat(mapped.get(3))
                .isEqualTo(new StudentTestCaseResponse.HiddenTest(4L, "Hidden test 2", TestVisibility.HIDDEN, 4));
    }

    @Test
    void nothingOfAHiddenTestSurvivesSerialisation() throws Exception {
        List<TestCase> tests = List.of(
                test(1, "public one", TestVisibility.PUBLIC, 1), test(2, SECRET_NAME, TestVisibility.HIDDEN, 2));

        String serialised = json.writeValueAsString(StudentTestCasesResponse.of(tests));

        assertThat(serialised).doesNotContain(SECRET_NAME, SECRET_INPUT, SECRET_OUTPUT);
        assertThat(serialised).contains("public one", "public in", "public out", "Hidden test 1");
    }

    @Test
    void aPublicTestIsShownInFullWithItsWeight() {
        var mapped = StudentTestCasesResponse.of(List.of(test(5, "p", TestVisibility.PUBLIC, 9)))
                .tests()
                .get(0);

        assertThat(mapped)
                .isEqualTo(new StudentTestCaseResponse.PublicTest(
                        5L, "p", "public in", "public out", TestVisibility.PUBLIC, 3, 9));
    }

    @Test
    void anEmptyListMapsToAnEmptyList() {
        assertThat(StudentTestCasesResponse.of(List.of()).tests()).isEmpty();
    }

    @Test
    void aStudentsHiddenNameDoesNotDependOnTheRealName() {
        var a = StudentTestCasesResponse.of(List.of(test(1, "alpha", TestVisibility.HIDDEN, 1)))
                .tests()
                .get(0);
        var b = StudentTestCasesResponse.of(List.of(test(2, "a completely different name", TestVisibility.HIDDEN, 5)))
                .tests()
                .get(0);

        assertThat(((StudentTestCaseResponse.HiddenTest) a).name())
                .isEqualTo(((StudentTestCaseResponse.HiddenTest) b).name());
    }
}
